// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtjxuirmzprcotkekxiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0anh1aXJtenByY290a2VreGl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTQwNTksImV4cCI6MjA2NTU5MDA1OX0.DsyTE9SQGaEcaWB72cnEvoTTi_xu3SioOggoVBLm9lc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);